name: Version Tag Automation

on:
  push:
    paths:
      - 'src/manifest.json'
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Get version
        id: version
        run: |
          VERSION=$(grep '"version"' src/manifest.json | cut -d'"' -f4)
          echo "::set-output name=version::$VERSION"
          
      - name: Create Tag
        run: |
          if ! git rev-parse "v${{ steps.version.outputs.version }}" >/dev/null 2>&1; then
            git tag -a "v${{ steps.version.outputs.version }}" -m "Version ${{ steps.version.outputs.version }}"
            git push origin "v${{ steps.version.outputs.version }}"
          fi

      - name: Check manifest version
        run: |
          if [[ ! "${{ steps.version.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid version format in manifest.json"
            exit 1
          fi
